### ISSUE TITLE
convert video to images

### ISSUE THREAD

**Issue by bobwan1995** [doc-doc/vRGV#3]
Hi, thanks for your interesting work! I want to follow your work, and firstly reimplement your result. I wonder how to get the codes that convert each raw video to images. Is it the same with the training and validation sets? Thank you!

**Comment by doc-doc** [comment]
Hi, pls use FFmpeg for extraction (others should be fine), and yes the train/val split follows the orginal dataset in VidVRD.

**Comment by bobwan1995** [comment]
Thanks for your reply. How do you uniformly extract 120 frames per video? Is there any compression on the extracted images? I would appreciate it if you could show me your original command(code) because I need to guarantee the input data is exactly the same as you to reimplement your result. Thank you so much!

**Comment by doc-doc** [comment]
I actually sampled 512 frames but 120 were finally used (because i had no idea how many frames are needed at the beginning). Pls refer to the code at [here](https://github.com/doc-doc/vRGV/blob/master/dataloader/util.py).  np.linspace() are used for sampling. The images are not rescaled. During feature extraction, we follow the standard in Faster R-CNN to resize the shortest edge to 800, pls refer to the related code in the feature extraction parts. Thanks

**Comment by doc-doc** [comment]
I actually sampled 512 frames but 120 were finally used (because i had no idea how many frames are needed at the beginning). Pls refer to the code  [here] (https://github.com/doc-doc/vRGV/blob/master/dataloader/util.py). np.linspace() are used for sampling. The images are not rescaled. During feature extraction, we follow the standard in Faster R-CNN to resize the shortest edge to 800, pls refer to the related code in the feature extraction parts. Thanks

**Comment by bobwan1995** [comment]
Thanks! What is the frame rate you used to extract videos? I observe there are many videos that only last 1 second and their default fps are 24-30, which means the frame count is less than 120. However, you mentioned you will sample 512(120) frames per video. So I want to know the frame rate you use, is it **_1_**. a fixed value (e.g. 120), or **_2_**. keep the same as the default value of the video?

If it's **_1_**, how can I get the corresponding annotation for val set? If it's **_2_**, how I can sample more than 120 frames when the video lasts for 1 sec(frame count less than 120)?

I will appreciate it if you could kindly show your original command that extracting video frames, which would avoid unnecessary misunderstandings. I think it might look like something below:
> ffmpeg -i ILSVRC2015_val_00072000.mp4 -r rate?  -q:v 2  ILSVRC2015_val_00072000/%06d.jpeg

**Comment by doc-doc** [comment]
Hi, you should extract all video frames according to the default frame rates, and then do frame sampling for model training. For videos with less frames, you should repeat some frames follow the sampling strategy in np.linspace().

**Comment by bobwan1995** [comment]
I got it. Thanks a lot! Furthermore, a higher version of pytorch(e.g. 1.6) is not compatible with this project because it will raise an error in "from torch.utils.ffi import create_extension" while compiling FasterRCNN, it's better to clarify this issue.

**Comment by doc-doc** [comment]
Thank you for the msg, i am recently too busy to maintain this repo. I tested it on 0.4 and 1.0, possibly you can find a solution yourself and would be appreciated if you can share it here..

**Comment by bobwan1995** [comment]
I tried to use pytorch1.0+cuda10.0 to compile FasterRCNN but will raise the same error. It works when I use pytorch0.4.1+cu90.
